id: I2A43BB2C
default_language: en
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:28:36.331124
last_modified: 2023-01-04 11:28:36.331138
source_metadata:
  collections:
  - Alak Zenkar Rinpoche
  - Works of Tibetan Masters
bases:
  '8400':
    title: Long Life Prayer for Alak Zenkar Rinpoche
    base_file: 8400.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
